"""empty message

Revision ID: 255c5bac84a2
Revises: 
Create Date: 2024-05-18 16:33:53.655911

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '255c5bac84a2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('account',
    sa.Column('id', sa.String(length=50), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated', sa.DateTime(timezone=True), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('dob', sa.Date(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('id')
    )
    with op.batch_alter_table('employe', schema=None) as batch_op:
        batch_op.drop_index('matricule_UNIQUE')

    op.drop_table('employe')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('username_UNIQUE')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom_complet', mysql.VARCHAR(length=70), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('username_UNIQUE', ['username'], unique=True)

    op.create_table('employe',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nom', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('prenom', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('matricule', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('fonction', mysql.VARCHAR(length=45), nullable=False),
    sa.Column('departement', mysql.VARCHAR(length=45), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('employe', schema=None) as batch_op:
        batch_op.create_index('matricule_UNIQUE', ['matricule'], unique=True)

    op.drop_table('account')
    # ### end Alembic commands ###
